### ISSUE TITLE
add functionality to set node object, facts, enviornment based on a remote source

### ISSUE THREAD

**Issue by logicminds** [nwops/puppet-repl#14]
Puppet has a feature (afaik) that can retrieve facts form either a master or puppetdb.  This would be awesome to be able to load the facts from a remote system in order to walk through code and hiera lookups.

**Comment by logicminds** [comment]
```
Puppet::Node::Facts.indirection.find('hostname')
Puppet::Node.indirection.find('hostname')
```

**Comment by logicminds** [comment]
```
Puppet::Node.indirection.find('pe-puppet.localdomain')
Puppet::Error: Could not retrieve facts for pe-puppet.localdomain: Error converting value for param 'pluginfactdest': Could not find value for $vardir
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1317:in `block in convert'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1306:in `gsub'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1306:in `convert'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1284:in `interpolate'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:1061:in `value'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/settings.rb:121:in `[]'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:63:in `[]'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/facts/facter.rb:82:in `setup_external_search_paths'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/facts/facter.rb:29:in `find'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:194:in `find'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/node.rb:117:in `fact_merge'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/node/plain.rb:17:in `find'
	from /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:194:in `find'
	from (irb):4
	from /opt/puppetlabs/puppet/bin/irb:11:in `<main>'

```

**Comment by logicminds** [comment]
```ruby
require 'puppet'
    def node_object(hostname)
      begin
        Puppet.initialize_settings
        Puppet[:trusted_node_data] = true
      rescue
        # do nothing otherwise calling init twice raises an error
      end
      Puppet::Node.indirection.find(hostname)
    end
```


```ruby
#<Puppet::Node:0x007fb6a321adc0
 @classes=[],
 @environment=
  #<Puppet::Node::Environment:0x007fb6a3036f68
   @attr_expirations={:modules=>2016-05-09 11:59:29 -0700},
   @config_version=nil,
   @manifest=:no_manifest,
   @modulepath=[],
   @name=:"*root*",
   @value_cache={:modules=>[]},
   @watching=true>,
 @expiration=2016-05-09 12:29:15 -0700,
 @facts=
  #<Puppet::Node::Facts:0x007fb6a2ba8708
   @expiration=2016-05-09 12:29:15 -0700,
   @name="pe-puppet.localdomain",
   @values=
    {"architecture"=>"x86_64",
     "kernel"=>"Darwin",
     "domain"=>"local",
     "virtual"=>"physical",
     "is_virtual"=>"false",
     "hardwaremodel"=>"x86_64",
     "operatingsystem"=>"Darwin",
     "os"=>"{\"name\"=>\"Darwin\", \"family\"=>\"Darwin\", \"release\"=>{\"major\"=>\"14\", \"minor\"=>\"5\", \"full\"=>\"14.5.0\"}}",
     "kernelrelease"=>"14.5.0",
     "facterversion"=>"2.4.6",
     "fqdn"=>"MacBook-Pro.local",
     "gid"=>"staff",
     "hardwareisa"=>"i386",
     "hostname"=>"MacBook-Pro",

```

**Comment by logicminds** [comment]
duplicate of #12
