### ISSUE TITLE
type display causes error

### ISSUE THREAD

**Issue by logicminds** [nwops/puppet-repl#21]
When typing `String` the repl quits the session trying to convert to something meaningful.

**Comment by logicminds** [comment]
```type([1,2,3,4])```

```
1:>> type([1,2,3,4])
/app/vendor/bundle/ruby/2.2.0/bundler/gems/puppet-repl-15062ed77974/lib/puppet-repl/cli.rb:58:in `to_resource_declaration': undefined m
ethod `[]' for nil:NilClass (NoMethodError)
        from /app/vendor/bundle/ruby/2.2.0/bundler/gems/puppet-repl-15062ed77974/lib/puppet-repl/cli.rb:88:in `normalize_output'
        from /app/vendor/bundle/ruby/2.2.0/bundler/gems/puppet-repl-15062ed77974/lib/puppet-repl/cli.rb:116:in `handle_input'
        from /app/vendor/bundle/ruby/2.2.0/bundler/gems/puppet-repl-15062ed77974/lib/puppet-repl/cli.rb:192:in `read_loop'
        from /app/vendor/bundle/ruby/2.2.0/bundler/gems/puppet-repl-15062ed77974/lib/puppet-repl/cli.rb:225:in `start'
        from /app/vendor/bundle/ruby/2.2.0/bundler/gems/puppet-repl-15062ed77974/bin/prepl:4:in `<top (required)>'
        from /app/vendor/bundle/bin/prepl:16:in `load'
        from /app/vendor/bundle/bin/prepl:16:in `<main>'
```
